### PR TITLE
HWKINVENT-38 + HAWKULAR-100

### PR DESCRIPTION
**Pull request by jkremser**
- [x]  Using the currentPersona.id as tenant for inventory.
- [x]  Moving the initialization code from pinger startup method to UI.

### CODE REVIEW

**Comment by jkremser** [comment]
This PR can be closed without merging, because this repo will be abandoned and forgotten :] New PR is here https://github.com/vrockai/hawkular/pull/2

**Comment by jpkrohling** [comment]
I believe this PR should have not been merged, as per @Jiri-Kremser 's comment. This should be reverted.

**Comment by mtho11** [comment]
It wan't marked 'Do not Merge Yet'. 
Anyway it won't make a difference now that https://github.com/hawkular/hawkular/pull/99 is merged.
@Jiri-Kremser please work with @vrockai  on Monday to resolve any issues.

**Comment by jkremser** [comment]
I don't know what are the plans with this repo, once it's content is now in hawkular/hawkular, either way, it shouldn't make any harm/difference if this PR is merged or not, IMO.
I'll ping Viliam on Monday..

**Comment by mtho11** [comment]
With Villiam's merge this repo is not being used at the moment since everything has been migrated to hawkular/ui/console now. We can use it for just reusable ui-components. But currently nothing is being used from it.

**Pull request merged**
