### PR TITLE
Rename module not to have small m

### PR DESCRIPTION
**Pull request by karelhala**
Module used to have big `Q` as third charactes, let's rename it to have small `q` so the name is now `miqStaticAssets`.

### CODE REVIEW

**Comment by abonas** [comment]
isn't the fix here changing Q to q? and there's an additional new code introduced in the commit?
I'm trying to understand what is the PR focusing on, it looks different than what the commit message says

**Comment by karelhala** [comment]
Yeah, I forgot to change the message when rebasing, going to change the commit message and PR info.

**Comment by abonas** [comment]
why is the code in hawkular-ui-components.js added in this PR?

**Comment by karelhala** [comment]
It's because of how bower works. Basically it downloads specific files from github so every time we want to make changes we also have to push files which are generated in build phase.

**Comment by mtho11** [comment]
It is a fairly standard practice to check in the resulting js product so that its available to bower (via git). For example, this is what Patternfly does.  Although strictly speaking it should not be not part of the commit. Ideally two solutions come to mind:
  a) Only build the js artifact on release (when we bump any of the version numbers)
  b) A bot(or build trigger) that builds the js artifacts after successful testing passes

**Comment by mtho11** [comment]
LGTM. The issues above are another different issue.

**Pull request merged**
