### PR TITLE
HAWKULAR-185 Add IDs for selenium to be able to log out (for QA)

### PR DESCRIPTION
**Pull request by jkremser**
just the ids

### CODE REVIEW

**Comment by pilhuhn** [comment]
Wasn't Sahi the cool child on the block? Or is that soooo 80ies ? :-)

**Comment by jkremser** [comment]
afaik, QA is playing with some "Test As a Service" tool (https://saucelabs.com/) That's probably why Selenium is cool again

**Comment by mtho11** [comment]
ID's are so jquery-ish.  Angular really has no need for them. It makes it harder to produce reusable components as well (multiple includes produce conflicts). I would not want to see us add a bunch of ids everywhere just so it can be tested. Can we ask QE to look at other ways to test components?

**Comment by jkremser** [comment]
In both cases all it does is just invoking `userDetails.logout()`. It's been a while I was working with Selenium, but it should be possible to run arbitrary JS code. Problem could be with the scoping, not sure how to get the stuff from angular scope without the browser extensions. There might be some Selenium plugin/web-driver for it, perhaps.

Other option could be addressing the element by some XPath or css selector (https://saucelabs.com/resources/selenium/css-selectors)

@ahovsepy could you comment, please?

**Comment by ahovsepy** [comment]
@Jiri-Kremser everything else with or without ID (with xpath, name, etc) is clickable, and the only problematic element is the logout one, which does not function on click. If that's not a good idea to put IDs for elements, then i guess we can skip it for logout link as well, and we'll try to "hack" it.

**Comment by mtho11** [comment]
@ahovsepy I think this logout ID is fine. Just wanted to make sure that we are not getting tons of requests for  ids on all of our elements.

**Pull request merged**
