### PR TITLE
Add Jasmine testing framework to project

### PR DESCRIPTION
**Pull request by mtho11**
After serious consideration to various testing frameworks the combination of Jasmine/mocha/chai to align with Rails RSpec tests was chosen.

### CODE REVIEW

**Comment by mtho11** [comment]
@Jiri-Kremser @ammendonca @karelhala  @abonas @pilhuhn 
Do you all agree with this choice?

http://jasmine.github.io/
https://mochajs.org/
http://chaijs.com/ (Jirka is the one who first drew my interest here)

Goal here is alignment with RSpec (although more narrow)

**Comment by karelhala** [comment]
I'd put protractor to the bundle as well. Since we have demo-app in the bundle we can test this app with protractor so we cover up whole spectrum.

However MiQ team is using jasmine, but I am totally fine with mocha and chai combination.

**Comment by mtho11** [comment]
@karelhala yeah, I agree with you, so I switched to jasmine and removed mocha/chai. We can add in chai later as a different PR.

**Comment by mtho11** [comment]
@pilhuhn please review/merge

**Pull request merged**
